In [111]:
#!/usr/bin/env python

# def greedy_search(graph,src,tgt):
#     """
#         Searches the adjacent nodes for the least distance, and keeps on doing it 
#         till it reaches the target
#     """
#     if not src in graph.keys():
#         raise AttributeError("The source '%s' is not in the graph" % src)
#     if not tgt in graph.keys():
#         raise AttributeError("The target '%s' is not in the graph" % tgt)

#     parents = {src: None}
#     path = [src] #path to store the result path from src to tgt 
#     node = src
#     while node != tgt:
#         distance_list=[]
#         for neighbor in graph[node].keys():
#             if neighbor not in parents:
#                 #check the best neighbor now
#                 temp_dis=graph[node][neighbor]
#                 distance_list.append((neighbor,temp_dis))

#         if distance_list==[]:
#             break
        
#         #finding the minimum of all distances
#         min_distance_of_neighbor=min(temp_dis for (neighbor,temp_dis) in distance_list)
        
#         #below is the code for finding the neighbor with the minimum distance
#         for (neigh,dis) in distance_list:
#             if dis == min_distance_of_neighbor:
#                 neighbor_with_the_minimum_distance=neigh
#                 break

#         #convert neighbor index into name 

#         #updating the parents list and new node for the next iteration
#         parents[neighbor_with_the_minimum_distance]=node
#         node=neighbor_with_the_minimum_distance
#         #updating the path with neighbor_with_the_minimum_distance
#         path.append(neighbor_with_the_minimum_distance)

#     return path

# defining graphs for our tests
# test1 -> graph1
# test2 -> graph2
# test3 -> graph3 
# test4 -> graph4

# Here, the letters represent the first letter of the cities 
# R -> Riyadh 
# A -> Abha 
# N -> Najran 
# J -> Jizan 
# S -> Samtah
# M -> Makkah 
# T -> Tabuk 
# Q -> Qurrayat
# D -> Dammam 

# here, each graph has entries of nodes/cities with its neighbours and their 
# distances as a dictionary inside a dictionary
# graph1={
#     'R':{'A':1064,'N':950},
#     'A':{'N':280,'J':202,'R':1064},
#     'N':{'A':280,'R':1064},
#     'J':{'A':202,'S':61},
#     'S':{'J':61}
# }

# graph2={
#     'R':{'D':395,'Q':1255,'T':1304,'M':870},
#     'D':{'Q':1443,'R':395},
#     'Q':{'R':1255,'D':1443,'T':570},
#     'T':{'Q':570,'R':1304,'M':1017},
#     'M':{'T':1017,'R':870}
# }

# graph3={
#     'R':{'D':395,'N':950,'A':1064},
#     'D':{'R':395,'N':1345},
#     'A':{'R':1064,'N':280,'J':202},
#     'N':{'R':950,'D':1345,'A':280},
#     'J':{'A':202}
# }

# graph4={
#     'R':{'M':870,'A':1064},
#     'M':{'R':870,'A':627,'J':680},
#     'A':{'R':1064,'M':627,'J':202},
#     'J':{'M':680,'S':61},
#     'S':{'J':61}
# }


# #Following are the input parameters
# graph=graph4
# src="R"
# dest="S"

# #invoke the greedy function
# result=greedy_search(graph,src,dest)

# print("Shortest path generated:")
# print(result)

# #print the total distance 
# a=src
# total_distance=0

# for i in range(len(result)-1):
#     total_distance+=graph[result[i]][result[i+1]]

# print("Minimum distance:")
# print(total_distance)


In [112]:
graph4={
    'R':{'M':870,'A':1064},
    'M':{'R':870,'A':627,'J':680},
    'A':{'R':1064,'M':627,'J':202},
    'J':{'M':680,'S':61},
    'S':{'J':61}
}
cities_enumerated=list(enumerate(graph4))
print(cities_enumerated)

#create a city to id dictionary
city_to_id={}
for i,j in cities_enumerated:
    city_to_id[j]=i

print(city_to_id)
# cities_enumerated_reverse=[(j,i) for (i,j) in cities_enumerated]
# print(cities_enumerated_reverse)

[(0, 'R'), (1, 'M'), (2, 'A'), (3, 'J'), (4, 'S')]
{'R': 0, 'M': 1, 'A': 2, 'J': 3, 'S': 4}


In [113]:
#converting adjancency list to adjacency matrix
matrix=[]
for i,city_name in cities_enumerated:
    list_of_distances_from_current_city=[99999]*len(graph4)
#     for city_id,city_name in cities_enumerated:
#         #make distance 0 for the current city
#         list_of_distances_from_current_city.insert(city_id,0)
# #         list_of_distances_from_current_city.insert(graph4)
    #distance from city to the same city is 0
    list_of_distances_from_current_city[i]=0
    
    #now check the dictionary containing this city 
    
    dictionary_of_distance_to_other_cities=graph4[cities_enumerated[i][1]]
#     print(dictionary_of_distance_to_other_cities)
    
    for neighbor in dictionary_of_distance_to_other_cities:
#             print(neighbor)
            #insert the distance to the neighbor at their right index
            list_of_distances_from_current_city[city_to_id[neighbor]]=dictionary_of_distance_to_other_cities[neighbor]

#     list_of_distances_from_current_city.insert()/
    matrix.append(list_of_distances_from_current_city)

print(matrix)

[[0, 870, 1064, 99999, 99999], [870, 0, 627, 680, 99999], [1064, 627, 0, 202, 99999], [99999, 680, 99999, 0, 61], [99999, 99999, 99999, 61, 0]]


In [114]:
# we have the cost (distance) matrix
# list of cities
cities=list(range(0,len(cities_names)))
starting_city=0

In [115]:
import numpy as np
graph=np.array(matrix)
print(graph)

[[    0   870  1064 99999 99999]
 [  870     0   627   680 99999]
 [ 1064   627     0   202 99999]
 [99999   680 99999     0    61]
 [99999 99999 99999    61     0]]


In [116]:
from numpy import argmin

In [117]:
# redefining the nearest neighbour heuristic

def nearest_neighbor_heuristic_route_generator(starting_city):
    """
        Greedy Nearest neighbor heuristic route generator
    """
    # maintain a list called 'visited' to store the cities that have been visited
    # initially, this holds the starting city
    visited=[]
    visited.append(starting_city)
    current_city=starting_city
    #also maintain a local copy of all the cities
    cities_copy=cities.copy()
    #remove the visited city from this list
    cities_copy.remove(starting_city)
    #total cost of the route
    total_cost=0
    
    # from the starting city, calculate the cost to every cities(except itself) and select the city with minimum cost
    while cities_copy !=[]:
        #calculate cost to every other cities in the cities_copy from the current city and store in cost_list
        cost_list=[]
        for neighbor_city in cities_copy:
            cost=matrix[current_city][neighbor_city]
            cost_list.append(cost)
        print(cost_list)
        min_idx=argmin(cost_list)#selects the index with the minimum cost
        print(min_idx) 
        #also add the min cost to the total cost
        total_cost+=min(cost_list)
        #now find the corresponding city (neighbor)
        corresponding_city=cities_copy[min_idx]
        # add that to the visited list
        visited.append(corresponding_city)
        # remove that from the cities_copy list
        cities_copy.remove(corresponding_city)
        # change current city to the city with min cost (corresponding city)
        current_city=corresponding_city
        
    # last city has to be connected to the starting city so let's do that
    total_cost+=matrix[current_city][starting_city] #add to total cost
    visited.append(starting_city)
    
    return total_cost,visited
        

#display the result for the data
total_cost,route_generated=nearest_neighbor_heuristic_route_generator(0)
        
print("Total cost:",total_cost)
print("Route generated:",route_generated)
    
    
    
    
    

[870, 1064, 99999, 99999]
0
[627, 680, 99999]
0
[202, 99999]
0
[61]
0
Total cost: 101759
Route generated: [0, 1, 2, 3, 4, 0]


In [118]:
#improve the route generated with 2-opt swap algorithm 
dist_mat = matrix
route_finder = RouteFinder(dist_mat, route_generated, iterations=20)
best_distance, best_route = route_finder.solve()
print(best_distance,best_route)

0 msec
0 msec
0 msec
1 msec
1 msec
2 msec
2 msec
3 msec
3 msec
3 msec
3 msec
3 msec
3 msec
5 msec
6 msec
6 msec
6 msec
6 msec
6 msec
6 msec
1760.0 [0, 1, 2, 3, 4]


In [119]:
def _swap_2opt(route, i, k):
    """ 
    Swapping the route 
    """
    new_route = route[0:i]
    new_route.extend(reversed(route[i:k + 1]))
    new_route.extend(route[k + 1:])
    return new_route


In [120]:
def route_cost(graph, path):
    
    cost = 0
    for index in range(len(path) - 1):
        cost = cost + graph[path[index]][path[index + 1]]
    # add last edge to form a cycle.
    cost = cost + graph[path[-1], path[0]]
    return cost

In [121]:
# implement the 2-opt heuristic to improve the returned greedy route

def tsp_2_opt(graph, route):
    """
    Approximate the optimal path of travelling salesman according to 2-opt algorithm
    Args:
        graph: 2d numpy array as graph
        route: list of nodes

    Returns:
        optimal path according to 2-opt algorithm

    Examples:
        >>> import numpy as np
        >>> graph = np.array([[  0, 300, 250, 190, 230],
        >>>                   [300,   0, 230, 330, 150],
        >>>                   [250, 230,   0, 240, 120],
        >>>                   [190, 330, 240,   0, 220],
        >>>                   [230, 150, 120, 220,   0]])
        >>> tsp_2_opt(graph)
    """
    improved = True
    best_found_route = route
    best_found_route_cost = route_cost(graph, best_found_route)
    while improved:
        improved = False
        for i in range(1, len(best_found_route) - 1):
            for k in range(i + 1, len(best_found_route) - 1):
                new_route = _swap_2opt(best_found_route, i, k)
                new_route_cost = route_cost(graph, new_route)
                if new_route_cost < best_found_route_cost:
                    best_found_route_cost = new_route_cost
                    best_found_route = new_route
                    improved = True
                    break
            if improved:
                break
    return best_found_route_cost,best_found_route


In [122]:
print(tsp_2_opt(graph,route_generated))

(101759, [0, 1, 2, 3, 4, 0])


## Redefining our greedy nearest-neighbor heuristic for the data from the DP solution

In [123]:
# using the matrix from the DP approach
matrix = [
            [0,          0.268188,   1.0861600,  0.284266,  2.1870300, 2.90507,  1.06443,    0.641625,   0.191624, 3.44142],
            [0.1609330,      0,      0.6911510,  0.464564,  1.4049800, 1.96431,  0.168696,   0.654258,   1.41509,  2.98196],
            [0.3580770,  0.379707,       0,      1.249930,  0.0821726, 0.408356, 1.74232,    2.37079,    2.95341,  3.90037],
            [0.0818823,  0.223001,   1.0921200,     0,      2.1872100, 2.89526,  0.942284,   0.56915,    0.872503, 2.75427],
            [0.3714430,  0.397651,   0.0423335,  1.289620,      0,     0.315516, 1.82914,    2.46966,    3.06793,  3.87276],
            [0.4166200,  0.46945,    0.1776410,  1.441470,  0.2664210,      0,   2.15881,    2.82956,    3.44337,  3.90929],
            [0.1427810,  0.0377101,  0.7089300,  0.438806,  1.4446600, 2.01924,     0,       0.526249,   1.24782,  3.13342],
            [0.0799607,  0.135875,   0.8962080,  0.246239,  1.8121500, 2.45884,  0.488912,       0,      0.76215,  3.14592],
            [0.0228630,  0.281361,   1.0688800,  0.361399,  2.1552200, 2.86474,  1.10989,    0.729676,       0,    3.6366],
            [0.4020280,  0.580519,   1.3821200,  1.117020,  2.6638000, 3.18444,  2.72886,    2.94897,    3.56066,    0],
]

# data points
data = [0,1, 2, 3, 4, 5, 6, 7, 8, 9]

In [124]:
# redefining the nearest neighbour heuristic

def nearest_neighbor_heuristic_route_generator(starting_point):
    """
        Greedy Nearest neighbor heuristic route generator
    """
    # maintain a list called 'visited' to store the cities that have been visited
    # initially, this holds the starting city
    visited=[]
    visited.append(starting_point)
    current_point=starting_point
    #also maintain a local copy of all the cities
    data_copy=data.copy()
    #remove the visited city from this list
    data_copy.remove(starting_point)
    #total cost of the route
    total_cost=0
    
    # from the starting city, calculate the cost to every cities(except itself) and select the city with minimum cost
    while data_copy !=[]:
        #calculate cost to every other cities in the cities_copy from the current city and store in cost_list
        cost_list=[]
        for neighbor_point in data_copy:
            cost=matrix[current_point][neighbor_point]
            cost_list.append(cost)
        print(cost_list)
        min_idx=argmin(cost_list)#selects the index with the minimum cost
        print(min_idx) 
        #also add the min cost to the total cost
        total_cost+=min(cost_list)
        #now find the corresponding point (neighbor)
        corresponding_point=data_copy[min_idx]
        # add that to the visited list
        visited.append(corresponding_point)
        # remove that from the data_copy list
        data_copy.remove(corresponding_point)
        # change current city to the city with min cost (corresponding city)
        current_point=corresponding_point
        
    # last city has to be connected to the starting city so let's do that
    total_cost+=matrix[current_point][starting_point] #add to total cost
    visited.append(starting_point)
    
    return total_cost,visited
        

#display the result for the data
total_cost,route_generated=nearest_neighbor_heuristic_route_generator(0)
        
print("Total cost:",total_cost)
print("Route generated:",route_generated)
    

[0.268188, 1.08616, 0.284266, 2.18703, 2.90507, 1.06443, 0.641625, 0.191624, 3.44142]
7
[0.281361, 1.06888, 0.361399, 2.15522, 2.86474, 1.10989, 0.729676, 3.6366]
0
[0.691151, 0.464564, 1.40498, 1.96431, 0.168696, 0.654258, 2.98196]
4
[0.70893, 0.438806, 1.44466, 2.01924, 0.526249, 3.13342]
1
[1.09212, 2.18721, 2.89526, 0.56915, 2.75427]
3
[0.896208, 1.81215, 2.45884, 3.14592]
0
[0.0821726, 0.408356, 3.90037]
0
[0.315516, 3.87276]
0
[3.90929]
0
Total cost: 7.254851599999999
Route generated: [0, 8, 1, 6, 3, 7, 2, 4, 5, 9, 0]


In [125]:
print("Total cost (greedy):",total_cost)
print("Route generated:",route_generated)

Total cost (greedy): 7.254851599999999
Route generated: [0, 8, 1, 6, 3, 7, 2, 4, 5, 9, 0]


In [126]:
#apply 2-opt 
print(tsp_2_opt(np.array(matrix),route_generated))

(6.844680599999999, [0, 8, 3, 7, 1, 6, 2, 4, 5, 9, 0])
