# Ant Colony Optimization based Itinerary Recommender

## "The title is pretty much self-explanatory. We will be following the ACO framework shown below:"

###### ACO Framework 

% Create Graph

% Draw Graph

%% ACO algorithm

    % Define Initial Parameters
    
    % Main loop
    
    for i = 1 to max_iter:
        % Create ants
        % Calculate fitness value of all ants
        % Find the best ant 
        % Update the pheromone matrix
        % Implement Evaporation
        % Display results 
    end

In [1]:
# Import the libraries 

import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

In [5]:
# Import the dataset
top_dests=pd.read_csv("../../Datasets/final_destinations_of_ktm_latest.csv")

In [3]:
print(top_dests.head())

   Unnamed: 0  dest_id                 title  \
0           0        1      Boudhanath Stupa   
1           1        2  Swayambhunath Temple   
2           2        3  Pashupatinath Temple   
3           3        4     Chandragiri Hills   
4           4        5       Kopan Monastery   

                                    genre   latitude  longitude  \
0  history:art_and_architecture:religious  27.721506  85.359809   
1  history:art_and_architecture:religious  27.714930  85.288146   
2  history:art_and_architecture:religious  27.710446  85.346503   
3                                  nature  27.671050  85.262664   
4  history:art_and_architecture:religious  27.742544  85.362208   

                                             img_url  
0  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...  
1  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...  
2  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...  
3  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...  
4  data:image/jpeg;base64,/9j/4AA

In [9]:
# drop the first column (index)
print(top_dests.columns)
top_dests=top_dests.drop(['Unnamed: 0'],axis=1)
print(top_dests)

Index(['Unnamed: 0', 'dest_id', 'title', 'genre', 'latitude', 'longitude',
       'img_url'],
      dtype='object')
      dest_id                                title  \
0           1                     Boudhanath Stupa   
1           2                 Swayambhunath Temple   
2           3                 Pashupatinath Temple   
3           4                    Chandragiri Hills   
4           5                      Kopan Monastery   
...       ...                                  ...   
2328     2341         Zeal Nepal Trek & Expedition   
2329     2342                        Mohit Sunuwar   
2330     2343  SITA (Travel Corporation India Ltd)   
2331     2344                       Himalayan Hike   
2332     2345                            River Fun   

                                           genre   latitude  longitude  \
0         history:art_and_architecture:religious  27.721506  85.359809   
1         history:art_and_architecture:religious  27.714930  85.288146   
2         his

In [54]:
top_dests.to_csv("../../Datasets/final_destinations_of_ktm_latest.csv")

In [14]:
# select the first 189 destinations as they're the destinations having the latitude and longitude currently
top_dests=top_dests[:189]

In [15]:
print(top_dests.tail())

     dest_id                                title  \
184      197  Nepal Alibaba Treks & Tours Pvt Ltd   
185      198                  Alpine Ramble Treks   
186      199      Info Nepal Treks and Expedition   
187      200          Epic Adventures - Day Tours   
188      201               Hiking Adventure Treks   

                                          genre   latitude  longitude img_url  
184                                     history  27.737544  85.302841     NaN  
185                                     history  27.719162  85.306492     NaN  
186  history:art_and_architecture:entertainment  27.716040  85.308885     NaN  
187              art_and_architecture:religious  27.700972  85.280179     NaN  
188  history:art_and_architecture:entertainment  27.717671  85.309687     NaN  


In [16]:
# since we'll be dealing only with latitude and longitude at the moment
# only filter those columns along with the title
print(top_dests[['title','latitude','longitude']])

                                   title   latitude  longitude
0                       Boudhanath Stupa  27.721506  85.359809
1                   Swayambhunath Temple  27.714930  85.288146
2                   Pashupatinath Temple  27.710446  85.346503
3                      Chandragiri Hills  27.671050  85.262664
4                        Kopan Monastery  27.742544  85.362208
..                                   ...        ...        ...
184  Nepal Alibaba Treks & Tours Pvt Ltd  27.737544  85.302841
185                  Alpine Ramble Treks  27.719162  85.306492
186      Info Nepal Treks and Expedition  27.716040  85.308885
187          Epic Adventures - Day Tours  27.700972  85.280179
188               Hiking Adventure Treks  27.717671  85.309687

[189 rows x 3 columns]


In [17]:
# # let's plot the graph again 
# %matplotlib inline 
# plt.figure(figsize=(12,12)) 

# for lat,long in zip(top_dests['latitude'],top_dests['longitude']):
    
#     for another_lat,another_long in zip(top_dests['latitude'],top_dests['longitude']):
        
#         # create a list holding the two latitude
#         lat_list=[lat,another_lat]
#         # also create a list holding the two longitudes 
#         long_list=[long,another_long]
#         plt.plot(lat_list,long_list,color='blue', marker='o', linestyle='solid',linewidth=2, markersize=8,mfc = 'white')
# #     plt.plot(lat_list,top_n_dests['longitude'],color='blue', marker='o', linestyle='solid',linewidth=2, markersize=8,mfc = 'white')

# for title,x,y in zip(top_dests['title'],top_dests['latitude'],top_dests['longitude']):

#     label = "{}".format(title)

#     plt.annotate(label, # this is the text
#                  (x,y), # these are the coordinates to position the label
#                  textcoords="offset points", # how to position the text
#                  xytext=(0,10), # distance from text to points (x,y)
#                  ha='center') # horizontal alignment can be left, right or center
# plt.show()

In [18]:
# let's just pick n=189 
n=189 #graph size
top_n_dests=top_dests[:n]
print(top_n_dests)

# define a starting point 
starting_point=0

     dest_id                                title  \
0          1                     Boudhanath Stupa   
1          2                 Swayambhunath Temple   
2          3                 Pashupatinath Temple   
3          4                    Chandragiri Hills   
4          5                      Kopan Monastery   
..       ...                                  ...   
184      197  Nepal Alibaba Treks & Tours Pvt Ltd   
185      198                  Alpine Ramble Treks   
186      199      Info Nepal Treks and Expedition   
187      200          Epic Adventures - Day Tours   
188      201               Hiking Adventure Treks   

                                          genre   latitude  longitude  \
0        history:art_and_architecture:religious  27.721506  85.359809   
1        history:art_and_architecture:religious  27.714930  85.288146   
2        history:art_and_architecture:religious  27.710446  85.346503   
3                                        nature  27.671050  85.262664  

In [34]:
# remove the duplicate entry

print(len(top_n_dests['latitude'].unique()))
print(len(top_n_dests['longitude'].unique()))

#print out the duplicated latitude,longitude
duplicate_lat_long = top_n_dests[top_n_dests.duplicated(['latitude','longitude'])]
print(duplicate_lat_long)

#remove the duplicate entries, keeping only the first
top_n_dests=top_n_dests.drop_duplicates(subset=['latitude', 'longitude'], keep='first')
print(len(top_n_dests))
# print(top_n_dests[top_n_dests['latitude']=='27.7154575'])

185
185
     dest_id              title                                   genre  \
119      125  Woodcraft Gallery  history:art_and_architecture:religious   
121      127    Aviation Museum            history:art_and_architecture   
137      147      Shobabaghwati     history:art_and_architecture:nature   

      latitude  longitude img_url  
119  27.715457  85.306667     NaN  
121  27.693795  85.351280     NaN  
137  27.714930  85.288146     NaN  
186


In [53]:
#save to a dataset 
top_n_dests.to_csv("../../Datasets/final_dest_ktm_with_duplicates_removed.csv")

In [35]:
n=186 # had to change n too to 186 after removing the duplicates

In [36]:
def plot_graph(ax,fig):
    """
        Function to plot the graph of matrix for every edge between the given nodes
    """

    for lat,long in zip(top_n_dests['latitude'],top_n_dests['longitude']):
        for another_lat,another_long in zip(top_n_dests['latitude'],top_n_dests['longitude']):

            # create a list holding the two latitude
            lat_list=[lat,another_lat]
            # also create a list holding the two longitudes 
            long_list=[long,another_long]

            ax.plot(lat_list,long_list,color='blue', marker='o', linestyle='solid',linewidth=2, markersize=8,mfc = 'white')
            #     plt.plot(lat_list,top_n_dests['longitude'],color='blue', marker='o', linestyle='solid',linewidth=2, markersize=8,mfc = 'white')
            fig.canvas.draw()
            
    #adding label to each node
    for title,x,y in zip(top_n_dests['title'],top_n_dests['latitude'],top_n_dests['longitude']):

        label = "{}".format(title)

        ax.annotate(label, # this is the text
                     (x,y), # these are the coordinates to position the label
                     textcoords="offset points", # how to position the text
                     xytext=(-5,5), # distance from text to points (x,y)
                     ha='center') # horizontal alignment can be left, right or center



In [37]:
# also meanwhile let's create a matrix called 'graph' to store the weights for each edges
graph=np.zeros((n,n))

# 
def create_graph():

    # iterators to iterate through the graph
    i=0
    j=0

    for lat,long in zip(top_n_dests['latitude'].astype(float),top_n_dests['longitude'].astype(float)):
        j=0
        for another_lat,another_long in zip(top_n_dests['latitude'].astype(float),top_n_dests['longitude'].astype(float)):
            #edge weight(Euclidean distance)
            distance_between_the_places=np.sqrt((lat-another_lat)**2+(long-another_long)**2)
            #print(distance_between_the_places)

            #and store it in the 'graph' matrix
            graph[i][j]=distance_between_the_places
            #increment j 
            j+=1

        #increment i
        i+=1

In [38]:
create_graph()
print(graph)

[[0.         0.07196422 0.01730239 ... 0.05121585 0.08223434 0.05026862]
 [0.07196422 0.         0.05852919 ... 0.02076949 0.01607098 0.02171472]
 [0.01730239 0.05852919 0.         ... 0.03803103 0.06699673 0.03751842]
 ...
 [0.05121585 0.02076949 0.03803103 ... 0.         0.0324203  0.00181725]
 [0.08223434 0.01607098 0.06699673 ... 0.0324203  0.         0.03390473]
 [0.05026862 0.02171472 0.03751842 ... 0.00181725 0.03390473 0.        ]]


In [39]:
# Define the initial parameters of ACO
max_iter=100 #max no of iterations
ant_no=10 #number of ants 

#initial pheromone concentration
tau_0=10*1/(n*np.mean(graph))

#initial pheromone matrix
tau = tau_0*np.ones((n,n))
print("Initial pheromone matrix (Tau):")
print(tau)

#desirability/quality of each edge,eta
eta=1/graph #inverse of cost (distance)
print("Desirability matrix (Eta):")
print(eta)

rho=0.05 #evaporation rate
alpha=2 #pheromone exponential parameter
beta=1 #edge desirabiltu/quality exponential parameter


Initial pheromone matrix (Tau):
[[0.6450435 0.6450435 0.6450435 ... 0.6450435 0.6450435 0.6450435]
 [0.6450435 0.6450435 0.6450435 ... 0.6450435 0.6450435 0.6450435]
 [0.6450435 0.6450435 0.6450435 ... 0.6450435 0.6450435 0.6450435]
 ...
 [0.6450435 0.6450435 0.6450435 ... 0.6450435 0.6450435 0.6450435]
 [0.6450435 0.6450435 0.6450435 ... 0.6450435 0.6450435 0.6450435]
 [0.6450435 0.6450435 0.6450435 ... 0.6450435 0.6450435 0.6450435]]
Desirability matrix (Eta):
[[         inf  13.89579436  57.79547534 ...  19.52520696  12.16037014
   19.89312809]
 [ 13.89579436          inf  17.08549118 ...  48.14755215  62.22394267
   46.05172062]
 [ 57.79547534  17.08549118          inf ...  26.29431683  14.92610228
   26.65357516]
 ...
 [ 19.52520696  48.14755215  26.29431683 ...          inf  30.84487323
  550.28109577]
 [ 12.16037014  62.22394267  14.92610228 ...  30.84487323          inf
   29.49441031]
 [ 19.89312809  46.05172062  26.65357516 ... 550.28109577  29.49441031
           inf]]


/tmp/ipykernel_6490/1501364078.py:14: RuntimeWarning: divide by zero encountered in true_divide
  eta=1/graph #inverse of cost (distance)


In [40]:
print(tau[2,:]**alpha)

[0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112
 0.41608112 0.41608112 0.41608112 0.41608112 0.41608112 0.4160

In [41]:
print(eta[2,:]**beta)

[5.77954753e+01 1.70854912e+01            inf 1.07951909e+01
 2.79845177e+01 2.57216568e+01 2.90825411e+01 3.69544626e+00
 2.35267341e+01 2.74553501e+01 9.64190155e+00 7.08735180e+00
 7.38031557e+00 1.25360477e+01 2.39614361e+01 2.45067304e+02
 1.23393973e+01 3.25762666e+01 3.25818548e+01 2.35501398e+01
 6.87737315e+00 1.79003876e+01 2.97881172e+01 8.48965890e+00
 1.89775738e+01 2.53394803e+01 1.32182935e+01 2.52922237e+01
 2.62012936e+01 4.89178811e+00 1.68081140e+01 2.38343266e+01
 8.13897748e+00 2.73031804e+01 1.23452097e+01 4.02541142e+01
 9.74101212e+00 5.36210835e+01 1.60165042e+01 1.02069494e+01
 2.43787287e+01 1.76717137e+01 2.58729003e+01 1.25161304e+01
 2.35370819e+01 9.90181263e+02 2.38932355e+01 8.13077797e+01
 5.09979350e+01 2.56139267e+01 5.74891383e+01 2.96382353e+01
 1.64259627e+01 2.07916622e+02 9.13698039e+00 3.22731952e+01
 1.60389760e+01 2.33943404e+01 2.53347666e+01 2.72437047e+01
 2.31330127e+01 2.90870144e+01 2.62989038e+01 2.40616635e+01
 1.92358154e+01 2.623952

## Now moving on to the main loop of ACO

In [42]:
# defining a function to create the ant colony 
def create_colony(graph,node_no,ant_no,tau,eta,alpha,beta,initial_node):
    """
        creates an ant colony
    """
    # create a list called 'colony'
    # inside it, there will be ants ( represented by the indices)
    # each position contains other list called 'tour' that contains
    # the tour completed by each ant
    colony=[[] for _ in range(ant_no)] #size of the colony=no of ants
    
    # Run iterations equal to the number of ants 
    for i in range(ant_no):
        
        # define the initial node
        # we should take it as a parameter actually 
        # but let's take it random for now
        # initial_node=np.random.randint(0,node_no)
        
        # nope we changed our mind 
        initial_node=initial_node
        colony[i].append(initial_node)
        
#         print(colony)
        
        for j in range(node_no-1):
            #to choose the rest of the nodes
            
            #current node is the last node in the list
            current_node=int(colony[i][-1])
#             print("current node:",current_node)
            
            #use the following formula to calculate the probability 
            p_all_nodes=(tau[current_node,:]**alpha)*(eta[current_node,:]**beta)
#             print("Prob:",p_all_nodes)
            
            #make the probability of the visited nodes 0
#             print("colony:",colony)
            for node in colony[i]:
                p_all_nodes[node]=0
                
            #calculate the final probability
            p=p_all_nodes/np.sum(p_all_nodes)
#             print("Sum prob:",np.sum(p_all_nodes))
#             print("final prob:",p)
            
            #Note: 'p'is a vector having size (1,node_no)   
#             print("probability vector:",p)
            
            #select the next node based on roulette wheel
            next_node=roulette_wheel(p)
            
            #append next node to the tour 
            #made by the ant in the colony
            colony[i].append(next_node)
            
        # to complete the tour, 
        # add the initial node to the end as well
        
        colony[i].append(initial_node)
    return colony

In [43]:
# let's implement the roulette wheel function
def roulette_wheel(prob_vec):
    """
        Selects the next node based on 
        the cumulative sum of the probabilities 
        in the probability vector
    """
    #cumulative version of the prob_vec (p)
    
    cum_sum_p=np.cumsum(prob_vec)
    
    #choose a random value from 0 to 1
    random_val=np.random.rand()
#     print("random value:",random_val)
    
    #choose the first index as next_node in the probability vector
    #that has value more or equal to the random_val
    
#     print("cum sum:",cum_sum_p)
    
    next_node = np.argwhere(cum_sum_p>=random_val)[0][0]
    
    #return the next_node
    return next_node
    

### Now. let's define a function that calculates the fitness value of the route calculated

In [44]:
def fitness_function(tour,graph):
    """
        calculates the fitness of the tour
        > basically, it's the sum of cost of all edges
        in the tour.
    """
    fitness=0
    
    for i in range(len(tour)-1):
        
        current_node=tour[i] # current node
        next_node=tour[i+1] # next node
        
        # add the cost of current edge (current_node->next_node)
        # to the overall fitness
        
        fitness = fitness + graph[current_node][next_node]
        
    return fitness

### And a function to draw Pheromone graph

In [45]:
def draw_pheromone(ax,fig,tau,graph):
    """
        Draws pheromone graph
    """
    ax.clear()

    # Maximum value of pheromone
    max_tau=np.max(tau)
    # Minimum value of pheromone
    min_tau=np.min(tau)
    
    # Normalize the tau matrix
    tau_normalized = (tau - min_tau)/(max_tau - min_tau)
    for lat,long,i in zip(top_n_dests['latitude'],top_n_dests['longitude'],range(len(graph))):
        for another_lat,another_long,j in zip(top_n_dests['latitude'],top_n_dests['longitude'],range(len(graph))):

            # create a list holding the two latitude
            lat_list=[lat,another_lat]
            # also create a list holding the two longitudes 
            long_list=[long,another_long]
            ax.plot(lat_list,long_list,color=(0,0,1-tau_normalized[i][j]), marker='o', linestyle='solid',linewidth=10*tau_normalized[i][j]+0.5, markersize=8,mfc = 'white')
            fig.canvas.draw()
            fig.canvas.flush_events()

    
    for title,x,y in zip(top_n_dests['title'],top_n_dests['latitude'],top_n_dests['longitude']):
        label = "{}".format(title)
        ax.annotate(label, # this is the text
                 (x,y), # these are the coordinates to position the label
                 textcoords="offset points", # how to position the text
                 xytext=(-5,5), # distance from text to points (x,y)
                 ha='center') # horizontal alignment can be left, right or center
    
            

### Also, a function to draw the best tour 

In [46]:
def draw_best_tour(ax,fig,best_tour,graph):
    """
        function to draw the best tour
    """
    ax.clear()

    for i in range(len(best_tour)-1):
        #extract the current node and the next node
        current_node=best_tour[i]
        next_node=best_tour[i+1]
        
        #draw a line between current node and next node
        
        #latitude and longitude of the current node
        lat_current,long_current=top_n_dests.iloc[current_node]['latitude'],top_n_dests.iloc[current_node]['longitude']
        
        #latitude and longitude of the next node
        lat_next,long_next=top_n_dests.iloc[next_node]['latitude'],top_n_dests.iloc[next_node]['longitude']
        
        lat_list=[lat_current,lat_next]
        long_list=[long_current,long_next]
        
        plt.plot(lat_list,long_list,color='green', marker='o', linestyle='solid',linewidth=2, markersize=8,mfc = 'white')
        fig.canvas.draw()
        fig.canvas.flush_events()

        
    #for annotation
    for title,x,y in zip(top_n_dests['title'],top_n_dests['latitude'],top_n_dests['longitude']):
        label = "{}".format(title)
        
        ax.annotate(label, # this is the text
                 (x,y), # these are the coordinates to position the label
                 textcoords="offset points", # how to position the text
                 xytext=(-5,5), # distance from text to points (x,y)
                 ha='center') # horizontal alignment can be left, right or center

### Also , a function to update the pheromone matrix

In [47]:
def update_pheromone(tau,colony,fitness_list):
    """
        function to update the pheromone matrix
    """
    node_no=len(colony[1])
    ant_no=len(colony)
    
    for i in range(ant_no):
        # for each ant
        for j in range(node_no-1):
            # for each node in the tour 
            current_node=colony[i][j]
            next_node=colony[i][j+1]
            
            tau[current_node,next_node]=tau[current_node,next_node]+1/fitness_list[i]
            tau[next_node,current_node]=tau[next_node,current_node]+1/fitness_list[i]
    
    return tau

In [48]:
import time

## Main ACO loop 

In [49]:
# Main loop

best_fitness=np.inf
best_tour=[]

# %matplotlib notebook

# fig = plt.figure(figsize=(10,10))
# ax1 = fig.add_subplot(131)
# ax2 = fig.add_subplot(132)
# ax3 = fig.add_subplot(133)

# ax1.title.set_text('Initial Mesh')
# ax2.title.set_text('Pheromone Graph Plot')
# ax3.title.set_text('Best Tour Plot')
# plt.ion()

# # plt.title("Pheromone graph plot:")
# fig.show()
# fig.canvas.draw()

#let's draw the initial graph (mesh) first
# plot_graph(ax1,fig)
time_in=time.time()
for i in range(max_iter):
    # create ant colony
    colony=[] # store it as a list
    colony=create_colony(graph,n,ant_no,tau,eta,alpha,beta,starting_point)
#     print(f"Iteration #{i}:")
#     print(colony)
    
    # initializing fitness_list
    fitness_list=[0]*ant_no
    
    # calculate the fitness value of all ants
    for ant_i in range(ant_no):
        fitness_list[ant_i]=fitness_function(colony[ant_i],graph)
        
#     print(fitness_list)
    
    # find the best ant 
    min_value=np.min(fitness_list)
    min_index=np.argmin(fitness_list) #best ant
    
    if min_value<best_fitness:
        # replace best_fitness even smaller min_value is found
        best_fitness=min_value
        best_tour=colony[min_index] #tour of the best ant
        
#     print("Best fitness: ",best_fitness)
#     print("Best tour: ",best_tour)
    
    # update phermone matrix
    tau=update_pheromone(tau,colony,fitness_list)
    
    # print("Updated pheromone matrix:",tau)
    
    # apply evaporation
    tau=(1-rho)*tau
    
    # print("Updated pheromone matrix:",tau)
    
    # plot the pheromone graph
    # draw_pheromone(ax2,fig,tau,graph)
    
    # plot the best tour
    # draw_best_tour(ax3,fig,best_tour,graph)

#     plt.subplot(1,3,1)
#     %matplotlib tk
#     plt.figure(1)
    
#     draw_pheromone(tau,graph)

    
    
# drawing the best tour plot 
# draw_best_tour(ax3,fig,best_tour,graph)

# drawing end pheromone graph
# draw_pheromone(ax2,fig,tau,graph)

# display the names of destinations in the last tour
# print("Best tour obtained:")
print(best_tour)
time_out=time.time()
print(time_out-time_in)
for i in best_tour:
    print(top_n_dests.iloc[i]["title"],end='')
    print("--->",end='')

[0, 73, 50, 111, 91, 133, 48, 37, 35, 102, 22, 4, 66, 94, 87, 32, 34, 132, 11, 7, 20, 23, 29, 112, 12, 36, 3, 89, 184, 16, 26, 88, 38, 56, 52, 1, 30, 153, 98, 64, 78, 129, 113, 24, 41, 126, 84, 18, 96, 82, 15, 45, 118, 2, 101, 93, 53, 103, 47, 156, 21, 106, 77, 43, 10, 181, 144, 170, 152, 142, 121, 104, 119, 179, 165, 145, 158, 173, 143, 120, 160, 162, 92, 148, 114, 115, 99, 157, 13, 172, 39, 134, 105, 54, 124, 97, 109, 95, 69, 100, 137, 128, 116, 62, 127, 135, 63, 117, 58, 70, 57, 110, 123, 60, 136, 76, 44, 46, 85, 19, 8, 79, 14, 31, 40, 122, 67, 25, 27, 42, 130, 59, 9, 61, 74, 90, 125, 80, 107, 55, 17, 51, 6, 155, 168, 71, 180, 147, 175, 72, 161, 176, 108, 159, 169, 177, 75, 171, 81, 140, 138, 49, 5, 28, 183, 65, 164, 163, 151, 185, 141, 150, 33, 174, 166, 154, 167, 139, 182, 86, 83, 178, 146, 149, 68, 131, 0]
14.348279237747192
Boudhanath Stupa--->Guru Lhakhang Monastery--->Boudha Stupa Thanka Center--->Sara Enterprises--->Jamchen Lhakhang Monastery--->Buddha Park--->Boudha Farmers 

In [50]:
# plt.savefig('sample.png')

In [51]:
#actual distance given by Vincenty distance using more accurate ellipsoidal models such as WGS-84 than Haversine
import geopy.distance
total_distance=0 #total actual distance

for i in range(len(best_tour)-1):
    coords_1 = (top_n_dests.iloc[best_tour[i]]["latitude"],top_n_dests.iloc[best_tour[i]]["longitude"])
    coords_2 = (top_n_dests.iloc[best_tour[i+1]]["latitude"],top_n_dests.iloc[best_tour[i+1]]["longitude"])
    
    #names of destinations connected
    src=top_n_dests.iloc[best_tour[i]]["title"]
    dest=top_n_dests.iloc[best_tour[i+1]]["title"]
    distance=geopy.distance.geodesic(coords_1, coords_2).km
    print (f'{str(src)+"->"+str(dest)}',distance)
    total_distance=total_distance+distance

print("Total distance(km): ",total_distance)

Boudhanath Stupa->Guru Lhakhang Monastery 0.0579728509975531
Guru Lhakhang Monastery->Boudha Stupa Thanka Center 0.10895537810120313
Boudha Stupa Thanka Center->Sara Enterprises 0.07504265981289523
Sara Enterprises->Jamchen Lhakhang Monastery 0.0674976965974918
Jamchen Lhakhang Monastery->Buddha Park 0.09779098307752371
Buddha Park->Boudha Farmers Market at Utpala Cafe 0.24780177611013213
Boudha Farmers Market at Utpala Cafe->Shechen Monastery 0.17521402809011333
Shechen Monastery->White Monastery 0.8939207857647852
White Monastery->Khawalung Monastery 1.1374089864885273
Khawalung Monastery->Pullahari Monastery 0.3471494011151022
Pullahari Monastery->Kopan Monastery 0.8250061123659818
Kopan Monastery->Gokarneshwor Mahadev Temple 2.3270370631625847
Gokarneshwor Mahadev Temple->Universal Crafts 2.4679375240075916
Universal Crafts->Sundarijal Water Falls 5.937172168497511
Sundarijal Water Falls->Vajrayogini Temple 4.815274716869781
Vajrayogini Temple->Templo de Changu Narayan 4.9135543336

Mountain Holiday Treks & Expedition->Ambition Himalaya Treks & Expeditions 0.02305105111080969
Ambition Himalaya Treks & Expeditions->Nepal Hiking Team 0.6506313586013437
Nepal Hiking Team->Alpine Ramble Treks 0.09180194969930279
Alpine Ramble Treks->Casino Rad 1.2838491523452853
Casino Rad->Millionaire's Club and Casino 0.6091448812747116
Millionaire's Club and Casino->Earthbound Expeditions 2.0081188271626704
Earthbound Expeditions->Nepal Horizon Treks & Expedition 0.014795325796175474
Nepal Horizon Treks & Expedition->Incredible Treks 0.09706056235151453
Incredible Treks->Music Museum of Nepal 2.1070022662881085
Music Museum of Nepal->Direction Exhibition & Convention Center 0.15201214758264234
Direction Exhibition & Convention Center->Boudhanath Stupa 5.642079853236588
Total distance(km):  569.9811370856065
